config/routes.rb
Rails.application.routes.draw do
  root    "sessions#home"
  get     '/signup',      to: 'users#new'
  post    '/signup',      to: 'users#create'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  get     '/budget',      to: 'budgets#show'
  post    '/newbudget',   to: 'budgets#create'
  post    '/budget',      to: 'budgets#edit'
  delete  '/budget',      to: 'budgets#destroy'
  get     '/init',        to: 'budgets#init'
  get     '/calendar',    to: 'months#show'
  post    '/bank',        to: 'months#edit'
  patch   '/reset/:id',   to: 'months#reset', as: 'reset'
  post    '/change/:dir', to: 'months#changemonth', as: 'change'
  post    '/newitem',     to: 'items#create'
  post    '/edititem',    to: 'items#edit'
  post    '/import',      to: 'transactions#create'
  patch   '/import',      to: 'transactions#newlist'
  get     '/import',      to: 'transactions#import'
  patch   '/transaction', to: 'transactions#update'
  
  get     '/canvas',      to: 'canvas#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :months,              only: [:show, :destroy]
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :user, touch: true
  has_many :days, dependent: :destroy
  has_many :items, through: :days, dependent: :destroy
  has_many :transactions
  validates :user, presence: true
  validates :firstday, presence: true
  validates :startbank, numericality: true
  validates :endbank, numericality: true, allow_nil: true
  validate :unique_dates_per_user, on: :create
  before_save :set_day
  
  def Month.findMonth(user, date = Date.current)
    date = Date.new(date.year, date.month, 1)
    if user.months.exists?({firstday: date})
      @month = user.months.find_by(firstday: date)
    else
      @month = user.months.create(firstday: date)
      @month.previousBank
      Day.populate(@month)
    end
    return @month
  end
  
  def loopDays
    looper = firstday
    while looper.month == firstday.month do
      yield(looper)
      looper = looper.tomorrow
    end
    looper = looper.yesterday
    return( looper.wday )
  end
  
  def previous
    @user = User.find(user_id)
    @user.months.find_by({ firstday: firstday << 1 })
  end
  
  def previousBank
    if previous
      self.update_attribute(:startbank, previous.endbank) if previous.endbank
    end
  end
  
  def distinctItems( cat )
    itemlist = []
    days.each do |d|
      d.items.where(category: cat).each do |x|
        itemlist.push( x.title ) unless itemlist.include?( x.title )
      end
    end
    return itemlist.sort
  end
  
  def status( title )
    symbol = 'check'
    days.each do |d|
      if d.day != 0
        d.items.where( title: title ).each do |x|
          symbol = 'calendar' if ( ( x.subtype != 'cash' ) && !x.actual ) || ( ( x.subtype == 'cash' ) && ( d.day > sync ) )
        end
      end 
    end 
    return symbol
  end
  
  private
    def set_day
      self.firstday = first_day(firstday)
    end
    
    def first_day(date)
      Date.new(date.year, date.month, 1)
    end
    
    def unique_dates_per_user
      if firstday
        monthValue = first_day(firstday)
        if Month.exists?({ firstday: monthValue, user_id: user_id })
          errors.add(:firstday, "cannot have multiple entries per month" )
        end
      end
    end
    
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  
  def show
    @item = @month.items.build
    @bank = @month.startbank
    @budget = @user.budgets.all
    @sync = @month.sync ? @month.sync : 0
  end
  
  def destroy
    oldmonth = Month.find(params[:id])
    date = oldmonth.firstday
    @user = current_user
    oldmonth.destroy
    newmonth = Month.findMonth(@user, date)
    oldmonth.transactions.each { |x| x.update_attributes({ month_id: newmonth.id, assigned: 0, entered: false }) }
    session[:month_id] = newmonth.id
    redirect_to calendar_url
  end
  
  def reset
    @month.previousBank
    redirect_to calendar_url
  end
  
  def edit
    if @month.update_attributes(month_params)
      flash[:success] = "Bank balance successfully updated"
      redirect_to calendar_url
    else
      flash[:danger] = @month.errors.full_messages.first
      redirect_to calendar_url
    end
  end
  
  def changemonth
    newmonth = params[:dir] == 'right' ? @month.firstday >> 1 : @month.firstday << 1
    @month = Month.findMonth(@user, newmonth)
    session[:month_id] = @month.id
    redirect_to calendar_url
  end
  
  private
    def month_params
      params.require(:month).permit(:startbank)
    end
    
    def correct_user
      @user = current_user
      if @user.init
        @month = current_month
        if(@month.user_id != @user.id)
          flash[:danger] = "Action not authorised"
          session[:month_id] = Month.findMonth(user).id
          redirect_to :back
        end
      else
        flash[:danger] = "Review/change budget and confirm before viewing calendar"
        redirect_to budget_path
      end
    end
  
end

app/helpers/months_helper.rb
module MonthsHelper
  
  def unscheduledSpent( title )
    dayzero = @month.days.find_by( day: 0 )
    @month.items.where(title: title).sum( :amount ) - dayzero.items.where(title: title).sum( :amount )
  end
  
  def spent( title, cat )
    total = 0
    @month.days.each do |d|
      total += d.items.where( title: title, category: cat ).sum( :amount ) if d.day != 0
    end
    return total
  end
  
  def budgeted( title, cat )
    budget = @user.budgets.find_by( title: title, category: cat )
    if budget
      return budget.amount * freq_type( budget.date, true )
    else
      return 0.to_d
    end
  end
  
  def budgetedTotal( cat )
    budget = 0
    @user.budgets.where( category: cat ).each { |x| budget += budgeted( x.title, x.category ) }
    return budget
  end
  
  def status( dif, cat )
    stat = dif >= 0 ? 'positive' : 'negative'
    stat = stat == 'positive' ? 'negative' : 'positive' if cat == 'check'
    stat = '' if dif == 0
    return stat
  end
end

app/views/months/_accordion.html.erb
<% cat = locals[:cat] %>
<% expandHeight = 155 - (@day.items.select(:category).distinct.count * 23) %>

<div class='panel panel-default <%= cat %>' data-toggle='collapse' data-parent='#accordion<%= @day.day %>' data-target='#collapse<%= @day.day.to_s + cat %>'>
  <div class='panel-heading <%= cat %>' role='tab' id='heading<%= @day.day.to_s + cat %>' >
    <h4 class='panel-title'>
      <a class='collapsed' role='button' data-toggle='collapse' data-parent='#accordion<%= @day.day %>' href='#collapse<%= @day.day.to_s + cat %>' aria-expanded='false' aria-controls='collapse<%= @day.day.to_s + cat %>'>
        <%= @day.items.where( category: cat ).sum("amount").to_money %>
        <%= fa_icon @day.categorySymbol( cat ) %>
      </a>
    </h4>
  </div>
  <div id='collapse<%= @day.day.to_s + cat %>' class='panel-collapse collapse' role='tabpanel' aria-labelledby='heading<%= @day.day.to_s + cat %>'>
    <div class='panel-body' style="max-height: <%= expandHeight %>px; overflow: auto">
    <% @day.items.where(category: cat).each do |i| %>
      <% if i.category == 'check' %>
        <% @bank += i.amount %>
      <% else %>
        <% @bank -= i.amount unless i.subtype == 'cash' %>
      <% end %>
      <div class='accordionItem <%= cat %>'>
        <% if i.actual %>
          <p class='name' data-toggle='tooltip' data-placement='top' title='<%= i.actual %>' style='cursor: default'>
        <% else %>
          <p class='name' data-toggle='modal' data-target='#edititem' onclick='dayform("edit", <%= @day.id %>, "<%= i.category %>", "<%= i.title %>", "<%= i.amount.to_money( '', false, '' ) %>", "<%= i.id %>")' >
        <% end %>
          <%= i.title %><span class='amount'><%= i.amount.to_money %> <%= fa_icon i.itemIcon %></span>
        </p>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/months/_arrow.html.erb
<%= link_to( change_path( locals[:dir] ), method: :post, class: 'arrowButton' ) { fa_icon 'chevron-' + locals[:dir] } %>

app/views/months/_bank.html.erb
<% style = locals[:y] ? "data-toggle='modal' data-target='#changebank'" : "style='cursor: default'" %>
<div class='total<%= ' negative' if @bank < 0 %>' <%= style.html_safe %> >
    <%= @bank.to_money %>
    <%= fa_icon "exclamation-circle", style: 'color: red' if locals[:x] %>
</div>

app/views/months/_blank.html.erb
<div class='dateCell grayed'>
  <% if x == display %>
    <p class='remaining'>Remaining:</p>
    <% @month.items.where(subtype: 'unscheduled').each do |i| %>
      <% budgeted = @budget.find_by(title: i.title).amount %>
      <% spent = unscheduledSpent i.title %>
      <% unscheduledRemainder = budgeted - spent %>
      <div class='budget' style='font-size: 12px; overflow: auto; padding: 2px; border-bottom: 1px solid #6666ff;'>
        <p class='name' data-toggle="tooltip" data-placement="top" title="Budget: <%= budgeted.to_d.to_money('', true) %> Spent: <%= spent.to_d.to_money('', true) %>">
          <%= i.title %><span class='amount'><%= unscheduledRemainder.to_d.to_money('', true) %></span>
        </p>
      </div>
    <% end %>
    <%= render "bank", locals: {x: false, y: true} %>
  <% end %>
</div>

app/views/months/_day.html.erb
<div class='row' style='margin-bottom: 20px'>

<% @month.firstday.wday.times do |x| %>
  <%= render partial: "blank", locals: {x: x, display: @month.firstday.wday - 1} %>
<% end %>

<% endDay = @month.loopDays do |l| %>
  <% dayWeek = l.wday %>
  <% @day = @month.days.find_by(day: l.day) %>
  <% weekend = l.workday? ? '' : ' weekend' %>
  
  <div class='dateCell<%= weekend %>'>
    <div class='dateTitle'><%= @day.day %></div>
    
    <% if @day.items.size > 0 %>
      <div class='panel-group' id='accordion<%= @day.day %>' role='tablist' aria-multiselectable='true'>
      <% CATEGORIES.each do |cat| %>
        <% if @day.items.where(category: cat).exists? %>
        
          <%= render "accordion", locals: { cat: cat } %>
        
        <% end %>
      <% end %>
      </div>
    <% end %>
    <div class='dropdown' style='padding-left: 3px'>
      <i class='fa fa-plus-square' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'></i>
      <ul class='dropdown-menu' aria-labelledby='dLabel'>
      <% CATEGORIES.each do |c| %>
        <li class='name' data-toggle='modal' data-target='#newitem' onclick='dayform("new", <%= @day.id %>, "<%= c %>")' >Add new <%= c %></li>
      <% end %>
      </ul>
    </div>
    <%= render 'bank', locals: { x: @day.isWrong } %>
  </div>
  
<% end %>

<% (6 - endDay.to_i).times do |x| %>
  <%= render partial: "blank", locals: {x: x, display: 0} %>
<% end %>

<% @month.update_attribute :endbank, @bank %>
</div>

app/views/months/_formdays.html.erb
<% formId = locals[:formId] %>
<% f = locals[:formObject] %>

<div class='row' style='margin-top: 10px; height: 200px'>
  <div class='radioDates col-xs-7 col-xs-offset-2'>
    <% 7.times do |x| %>
      <%= f.label("blank", Date::DAYNAMES[x][0], :class => 'radio', :style => "border: 1px solid white") %>
    <% end %>
    <br>
    <% @month.firstday.wday.times do %>
      <label class='blankdate'>0</label>
    <% end %>
    <% endDay = @month.loopDays do |l| %>
      <% dayId = @month.days.find_by(day: l.day).id %>
      <%= f.radio_button :day_id, dayId %>
      <%= f.label("day_id_" + (dayId).to_s, l.day, :class => 'radio') %>
      <%= '<br>'.html_safe if l.wday == 6 %>
    <% end %>
    <% (6 - endDay).times do %>
      <label class='blankdate'>0</label>
    <% end %>
  </div>
</div>

app/views/months/_itemform.html.erb
<% formtype = locals[:formtype] %>
<% thisUrl = formtype == 'new' ? newitem_path : edititem_path %>

<%= render "shared/modal", locals: { idName: formtype + 'item', name: 'Add new item', formFor: @item, formUrl: thisUrl } do |f| %>

  <%= render "shared/formItem" do %>
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'amount', :list => '' %>
  <% end %>
  
  <%= render "shared/formItem" do %>
    <%= f.label :amount %>
    <%= f.text_field :amount, :class => 'amount' %>
  <% end %>
  
  <%= f.hidden_field :category %>
  
  <%= render 'formdays', locals: { formId: 'newitem', formObject: f } %>
  
  <%= hidden_field_tag 'month_id', @month.id %>
  
  <% provide ("footer" + formtype + "item").to_sym do %>
    <button type='button' class='btn btn-default' data-dismiss='modal'>Cancel</button>
    <%= f.submit "Save Changes", :class => 'btn btn-primary' %>
    <% if formtype == 'edit' %>
      <%= f.hidden_field :id %>
      <%= f.submit "Delete", :class => 'btn btn-default', :name => 'delete', :style => 'float: left' %>
    <% end %>
  <% end %>
  
<% end %>

app/views/months/_modals.html.erb
<%= render "itemform", locals: { formtype: 'edit' } %>
<%= render "itemform", locals: { formtype: 'new' } %>

<%= render "shared/modal", locals: { idName: 'changebank', name: 'Change bank balance', formFor: @month, formUrl: bank_path } do |f| %>

  <%= render "shared/formItem" do %>
    <%= f.label :startbank, 'New amount' %>
    <%= f.text_field :startbank, :value => @month.startbank.to_money('', false, ''), :class => 'amount' %>
  <% end %>
  
  <%= f.hidden_field :id %>
  
  <% provide :footerchangebank do %>
    <button type='button' class='btn btn-default' data-dismiss='modal'>Cancel</button>
    <%= link_to "Previous month's balance", reset_path(@month), method: :patch, class: "btn btn-default" if @month.previous %>
    <%= f.submit "Save Changes", :class => 'btn btn-primary' %>
  <% end %>
  
<% end %>

<%= render "shared/modal", locals: { idName: 'csvimport', name: 'Upload CSV file', formFor: :transactions, formUrl: import_path } do |f| %>

  <p>Choose file with transaction records:</p>
  <%= render "shared/formItem" do %>
    <%= f.file_field :csvfile, :accept => '.csv' %>
  <% end %>
  
  <%= f.hidden_field :month_id, :value => @month.id %>
  
  <% provide :footercsvimport do %>
    <button type='button' class='btn btn-default' data-dismiss='modal'>Cancel</button>
    <%= f.submit "Submit File", :class => 'btn btn-primary' %>
  <% end %>
  
<% end %>

<% CATEGORIES.each do |x| %>
  <datalist id='<%= x %>'>
    <% @user.lists.where({ category: x }).each do |y| %>
      <option value='<%= y.title %>'>
    <% end %>
  </datalist>
<% end %>

app/views/months/_recap.html.erb
<% CATEGORIES.each do |cat| %>
  <% plannedTotal = 0.to_d %>
  <% actualTotal = 0.to_d %>
  <div class='row title'>
    <% displayTitle = cat == 'budget' ? cat.capitalize : cat.capitalize.pluralize %>
    <div class='col-xs-3'><%= displayTitle %></div>
    <div class='col-xs-3'><%= 'Planned' if cat == CATEGORIES[0] %></div>
    <div class='col-xs-3'><%= 'Actual' if cat == CATEGORIES[0] %></div>
    <div class='col-xs-3'><%= 'Difference' if cat == CATEGORIES[0] %></div>
  </div>
  <% @month.distinctItems( cat ).each do |x| %>
    <% actualspent = spent( x, cat ) %>
    <% budgettotal = budgeted( x, cat ) %>
    <% dif = budgettotal - actualspent %>
    <% stat = status( dif, cat ) %>
    <div class='row budgetList'>
      <% symbol = @month.status( x ) %>
      <% tooltip = symbol == 'check' ? 'All planned items have been syncronized' : 'Amount may change, some planned items not yet syncronized' %>
      <div class='col-xs-3' data-toggle='tooltip' data-placement='top' title='<%= tooltip %>'>
        <p><%= fa_icon symbol %> <%= x %></p>
      </div>
      <div class='col-xs-3'><%= budgettotal.to_money %></div>
      <div class='col-xs-3 <%= stat %>'><%= actualspent.to_money %></div>
      <div class='col-xs-3 <%= stat %>'><%= dif.to_money('') %></div>
    </div>
    <% plannedTotal += budgettotal %>
    <% actualTotal += actualspent %>
  <% end %>
  <div class='row budgetList net'>
    <% dif = plannedTotal - actualTotal %>
    <% stat = status( dif, cat ) %>
    <div class='col-xs-3'><%= displayTitle %> Total</div>
	  <div class='col-xs-3'><%= plannedTotal.to_money %></div>
    <div class='col-xs-3 <%= stat %>'><%= actualTotal.to_money %></div>
    <div class='col-xs-3 <%= stat %>'><%= dif.to_money('') %></div>
  </div>
<% end %>

app/views/months/show.html.erb
<% provide(:title, @month.firstday.strftime('%B %Y')) %>
<h1>
  <%= render 'arrow', locals: { dir: 'left' } %>
  <%= @month.firstday.strftime('%B %Y') %>
  <%= render 'arrow', locals: { dir: 'right' } %>
  <%= link_to "RESET", @month, method: :delete, data: { confirm: "This will remove all data associated with this month, and reset it to the default value. Proceed?" }, class: "tiny" %>
  <span class="tiny"> | </span>
  <span class="tiny" data-toggle="modal" data-target="#csvimport" style="padding-left: 10px">Import CSV</span>
</h1>

<% transactionCount = @month.transactions.where(entered: false).count %>
<% if transactionCount > 1 %>
  <p>There are <%= transactionCount %> unassigned transactions. <%= link_to "Click here to assign.", import_path %></p>
<% end %>

<div class='row'>
  <% 7.times do |x| %>
    <div class='dateCell topRow'><%= Date::DAYNAMES[x] %></div>
  <% end %>
</div>

<%= render "day" %>

<%= render "recap" %>

<%= render "modals" %>