config/routes.rb
Rails.application.routes.draw do
  root    "sessions#home"
  get     '/signup',      to: 'users#new'
  post    '/signup',      to: 'users#create'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  get     '/budget',      to: 'budgets#show'
  post    '/newbudget',   to: 'budgets#create'
  post    '/budget',      to: 'budgets#edit'
  delete  '/budget',      to: 'budgets#destroy'
  get     '/init',        to: 'budgets#init'
  get     '/calendar',    to: 'months#show'
  post    '/bank',        to: 'months#edit'
  patch   '/reset/:id',   to: 'months#reset', as: 'reset'
  post    '/change/:dir', to: 'months#changemonth', as: 'change'
  post    '/newitem',     to: 'items#create'
  post    '/edititem',    to: 'items#edit'
  post    '/import',      to: 'transactions#create'
  patch   '/import',      to: 'transactions#newlist'
  get     '/import',      to: 'transactions#import'
  patch   '/transaction', to: 'transactions#update'
  
  get     '/canvas',      to: 'canvas#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :months,              only: [:show, :destroy]
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user, touch: true
  validates :user, presence: true
  validates :category, inclusion: { in: CATEGORIES, message: "%{value} is not a valid category" }
  validates :subtype, inclusion: { in: SUBTYPES, message: "%{value} is not a valid subtype" }, allow_nil: true
  validates :title, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :date, inclusion: { in: 0..45, message: "invalid value" }
  
  private

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :logged_in_user, only: [:show]
  
  def show
    @user = current_user
    if @user.init
      @month = Month.findMonth(@user)
    else
      date = Date.current
      @month = @user.months.new( firstday: Date.new(date.year, date.month, 1) )
    end
    @budgets = @user.budgets.all
    @list = { :check    => [ nil ],
              :bill     => [ nil, "automatic" ],
              :budget   => [ nil, "cash", "unscheduled" ] }
    @budget = @user.budgets.build
  end
  
  def create
    #render plain: params.to_yaml
    @user = current_user
    budget = @user.budgets.new(budget_params)
    if budget.save
      @user.lists.create({title: budget.title, category: budget.category}) if @user.init
      flash[:success] = "Item added successfully"
      redirect_to budget_url
    else
      flash[:danger] = budget.errors.full_messages.first
      redirect_to budget_url
    end
  end
  
  def edit
    #render plain: params.to_yaml
    @user = current_user
    budget = Budget.find params[:budget][:id]
    if params[:delete]
      if budget.destroy
        flash[:success] = "Item deleted successfully"
        @user.lists.find_by({title: budget.title, category: budget.category}).destroy if @user.init
        redirect_to budget_url
      end
    else
      if budget.update_attributes(budget_params)
        @user.lists.create({title: budget.title, category: budget.category}) if @user.init
        flash[:success] = "#{budget.title} successfully updated"
        redirect_to budget_url
      else
        flash[:danger] = budget.errors.full_messages.first
        redirect_to budget_url
      end
    end
  end
  
  def init
    @user = current_user
    if @user.update_attribute( :init, true )
      @user.budgets.each do |b|
        @user.lists.create({title: b.title, category: b.category})
      end
      session[:month_id] = Month.findMonth(@user).id
    end
    redirect_to calendar_url
  end
  
  private
    def budget_params
      params.require(:budget).permit(:category, :subtype, :title, :amount, :date)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def show_frequency(x)
    if x
      "#{freq_type(x).capitalize} on #{day_string(x)}"
    end
  end
  
  def day_string(x)
    if x
      if x.between?(0, 6)
        return Date::DAYNAMES[x]
      elsif x.between?(7, 13)
        return Date::DAYNAMES[x - 7]
      else
        return "the #{(x - 13).ordinalize}"
      end
    end
  end
  
  def date_number(x)
    if x
      if x.between?(0, 6)
        return x
      elsif x.between?(7, 13)
        return x - 7
      else
        return x - 13
      end
    end
  end
  
  def freq_type( x, num = false )
    if x
      if x.between?(0, 6)
        return num ? 4 : 'weekly'
      elsif x.between?(7, 13)
        return num ? 2 : 'biweekly'
      else
        return num ? 1 : 'monthly'
      end
    end
  end
  
  def monthly(x)
    x + 13
  end
  
  def biweekly(x)
    x + 7
  end
  
end

app/views/budgets/_budgetform.html.erb
<% formtype = locals[:formtype] %>
<% thisUrl = formtype == 'new' ? newbudget_path : budget_path %>
<% idName = formtype + 'budget' %>
<% name = locals[:name] %>
<% formFor = locals[:formFor] %>
<% formUrl = locals[:formUrl] %>
<% cat = locals[:cat] %>
<% subcat = locals[:subcat] %>
<%# freqType = dateNumber ? freq_type( dateNumber ) : 'weekly' %>

<%= render "shared/modal", locals: { idName: idName, name: 'Add new budget item', formFor: @budget, formUrl: thisUrl } do |f| %>

  <%= render "shared/formItem" do %>
    <%= f.label :title %>
    <%= f.text_field :title, :class => 'amount' %>
  <% end %>
  
  <%= render "shared/formItem" do %>
    <%= f.label :amount %>
    <%= f.text_field :amount, :class => 'amount' %>
  <% end %>
  
  <div id='<%= formtype %>datehide' >
    <% frequencies = ['weekly', 'biweekly', 'monthly'] %>
    <ul class="nav nav-tabs" role="tablist">
      <% frequencies.each do |freq| %>
        <% active = freq == 'weekly' ? "active" : "" %>
        <li role="presentation" class="<%= active %>" id="<%= formtype + freq %>tab">
          <a href="#<%= idName + freq %>" aria-controls="<%= idName + freq %>" role="tab" data-toggle="tab"><%= freq.capitalize %></a>
        </li>
      <% end %>
    </ul>
    
    <div class="tab-content" id='<%= idName %>date'>
      <% frequencies.each do |freq| %>
        <% partialName = freq == "monthly" ? "shared/formdays" : "formweekdays" %>
        <% active = freq == 'weekly' ? " active" : "" %>
        <% offset = freq == "weekly" ? 0 : freq == "biweekly" ? 7 : 13 %>
        <div role="tabpanel" class="tab-pane<%= active %>" id="<%= idName + freq %>">
          <%= render partialName, locals: { formId: idName, formObject: f, offset: offset } %>
        </div>
      <% end %>
    </div>
  </div>
  
  <%= f.radio_button :date, 45, :style => 'display: none' %>
  <%= f.hidden_field :category %>
  <%= f.hidden_field :subtype %>

  <% provide "footer#{ idName }".to_sym do %>
    <button type='button' class='btn btn-default' data-dismiss='modal'>Cancel</button>
    <%= f.submit "Save Changes", :class => 'btn btn-primary' %>
    <% if formtype == 'edit' %>
      <%= f.hidden_field :id %>
      <%= f.submit "Delete", :class => 'btn btn-default', :name => 'delete', :style => 'float: left' %>
    <% end %>
  <% end %>
  
<% end %>

app/views/budgets/_budgetlist.html.erb
<div class='col-sm-6'>
  <% @list.each do | cat, subt | %>
    <h2>
      <%= cat == 'budget' ? cat.to_s.capitalize : cat.to_s.pluralize.capitalize %>
      <a style="font-size: 18px" data-toggle='modal' data-target='#newbudget' onclick='budgetform("new", "<%= cat %>")'><%= fa_icon "plus-square-o" %></a>
    </h2>
    <% subt.each do | subcat | %>
      <div class='row' style='margin: 0 0 0 20px' >
      <% if subcat %>
        <h3>
          <%= subcat.capitalize %>
          <a style="font-size: 18px" data-toggle='modal' data-target='#newbudget' onclick='budgetform("new", "<%= cat %>", "<%= subcat %>")'>
            <%= fa_icon "plus-square-o" %>
          </a>
        </h3>
      <% end %>
      <% bud = @budgets.where( category: cat, subtype: subcat ) %>
      <% bud.each do | budget | %>
        <a style='color: black' data-toggle='modal' data-target='#editbudget' 
          onclick='budgetform("edit", "<%= budget.category %>", "<%= budget.subtype %>", "<%= budget.title %>", "<%= budget.amount.to_money( '', false, '' ) %>", "<%= budget.id %>", "<%= budget.date %>", "<%= freq_type budget.date %>" )'>
          <p class='name'>
            <%= budget.title %>
            <span class='frequency'><%= show_frequency(budget.date) %></span>
            <span class='amount'><%= budget.amount.to_money %></span>
          </p>
        </a>
      <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/budgets/_formweekdays.html.erb
<% formId = locals[:formId] #Date::DAYNAMES[x][0] %>
<% offset = locals[:offset] ? locals[:offset] : 0 %>
<% f = locals[:formObject] %>

<div class='row' style='margin-top: 10px; height: 200px'>
  <div class='radioDates col-xs-7 col-xs-offset-2'>
    <% 7.times do |x| %>
      <%= f.radio_button :date, x + offset %>
      <%= f.label("date_" + (x + offset).to_s, Date::DAYNAMES[x][0], :class => 'radio') %>
    <% end %>
  </div>
</div>

app/views/budgets/_recap.html.erb
<div class='col-sm-6'>
  <% income = budgetedTotal( 'check' ) %>
  <% bills = budgetedTotal( 'bill' ) %>
  <% budgets = budgetedTotal( 'budget' ) %>
  <% netTotal = income - (bills + budgets) %>
  <% stat = status( netTotal, '' ) %>
  <div class='row title' style='margin-bottom: 5px'>
    <div class='col-xs-6'>Income Total</div>
    <div class='col-xs-6'><%= income.to_money %></div>
  </div>
  <div class='row budgetList'>
    <div class='col-xs-6'>Bills</div>
    <div class='col-xs-6'><%= bills.to_money %></div>
  </div>
  <div class='row budgetList'>
    <div class='col-xs-6'>Budget</div>
    <div class='col-xs-6'><%= budgets.to_money %></div>
  </div>
  <div class='row title' style='margin-top: 0px'>
    <div class='col-xs-6'>Spending Total</div>
    <div class='col-xs-6 <%= stat %>'><%= ( bills + budgets ).to_money %></div>
  </div>
  <div class='row budgetList net' style='font-size: 24px'>
    <div class='col-xs-6'>Net Total</div>
    <div class='col-xs-6 <%= stat %>'><%= netTotal.to_money %></div>
  </div>
</div>

app/views/budgets/show.html.erb
<% provide(:title, "Edit Budget Plan") %>
<div class='row'>
  <h1 style="margin-bottom: 5px">
    Edit budget plan
  </h1>
  <p style="margin-left: 15px"><i>Click an item to edit</i></p>
</div>

<div class='row'>
  <%= render "budgetlist" %>
  <%= render "recap" %>
</div>

<% if !@user.init %>
  <div class='row' style='margin-top: 20px'>
    <div class='col-sm-6' style='text-align: center;'>
      <p style='text-align: center'><em>Don't click until initial budget changes have been made.</em></p>
      <a href='<%= init_path %>' class='btn btn-primary'>Initialize Budget</a>
    </div>
  </div>
<% end %>

<%= render "budgetform", locals: { formtype: 'edit' } %>
<%= render "budgetform", locals: { formtype: 'new' } %>