config/routes.rb
Rails.application.routes.draw do
  root    "sessions#home"
  get     '/signup',      to: 'users#new'
  post    '/signup',      to: 'users#create'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  get     '/budget',      to: 'budgets#show'
  post    '/newbudget',   to: 'budgets#create'
  post    '/budget',      to: 'budgets#edit'
  delete  '/budget',      to: 'budgets#destroy'
  get     '/init',        to: 'budgets#init'
  get     '/calendar',    to: 'months#show'
  post    '/bank',        to: 'months#edit'
  patch   '/reset/:id',   to: 'months#reset', as: 'reset'
  post    '/change/:dir', to: 'months#changemonth', as: 'change'
  post    '/newitem',     to: 'items#create'
  post    '/edititem',    to: 'items#edit'
  post    '/import',      to: 'transactions#create'
  patch   '/import',      to: 'transactions#newlist'
  get     '/import',      to: 'transactions#import'
  patch   '/transaction', to: 'transactions#update'
  
  get     '/canvas',      to: 'canvas#show'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :months,              only: [:show, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= fullTitle(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body><div id="holder">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <%= link_to "budget app", root_path, id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "View Calendar", calendar_path %></li>
            <li><%= link_to "Edit Budget", budget_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit account", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
            <li><a>or</a></li>
            <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>
    
    <div id="body"><div class='container'>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div></div>
    
    <% if Rails.env.development? %>
      <%= debug(params) %>
      <%= request.session.to_hash.each{|key, value| puts "#{key.to_s} --> #{value.to_s}"} %>
    <% end %>
  </div></body>
</html>